python_library(
   name="myapp_lib",
)

python_binary(
   name="myapp_bin",      
   dependencies=[":myapp_lib"] #  will uncomment when I figure this out, "//other_proj:other_proj_lib"],
   entry_point="main"
)
